version: '3.8'

services:
  backend-api:
    container_name: pakualaman-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:alpine3.19
    container_name: pakualaman-db
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - pakualaman_db:/var/lib/postgresql/data

volumes:
  pakualaman_db:
    name: pakualaman-app