name: CI/CD Pipeline Backend Pakualaman

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: docker build --build-arg AT_SECRET=${{ secrets.AT_SECRET }} --build-arg RT_SECRET=${{ secrets.RT_SECRET }} --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t nugrohoarr/bepakualaman:v1 .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push nugrohoarr/bepakualaman:v1

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
            export AT_SECRET=${{ secrets.AT_SECRET }}
            export RT_SECRET=${{ secrets.RT_SECRET }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export SUPERADMIN_EMAIL=${{ secrets.SUPERADMIN_EMAIL }}
            cd /root/be-sistem-penjurian-jemparingan
            ./deploy.sh
